apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jumpstarter-gitops-cluster-role
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jumpstarter-access-role
rules:
  - apiGroups: ["jumpstarter.dev"]
    resources:
      - clients
      - exporteraccesspolicies
      - exporters
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---