FROM ghcr.io/astral-sh/uv:latest AS uv

FROM quay.io/rhadp/builder:latest

COPY --from=uv /uv /uvx /bin/

# set the virtual environment for jumpstarter etc
ENV UV_PYTHON=python3.12 VIRTUAL_ENV=/venv

# install jumpstarter
RUN uv venv /venv && \
    uv pip install "git+https://github.com/jumpstarter-dev/jumpstarter#subdirectory=packages/jumpstarter-all"

# install ansible
RUN uv venv /venv && \
    uv pip install ansible boto3

ENV PATH="/venv/bin:$PATH"