FROM quay.io/rhadp/builder:latest

USER root

COPY --from=ghcr.io/astral-sh/uv:latest /uv  /bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /bin/uvx

# set the virtual environment for jumpstarter etc
ENV UV_PYTHON=python3.12 VIRTUAL_ENV=/venv

# install jumpstarter and other python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv venv /venv && \
    uv pip install "git+https://github.com/jumpstarter-dev/jumpstarter#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

ENV PATH="/venv/bin:$PATH"

# create jumpstarter client config directories
RUN mkdir -p /home/user/.config/jumpstarter/clients

# set permissions on the user's home directory
RUN chgrp -R 0 /home/user && \
    chmod -R g=u /home/user && \
    chown -R 10001 /home/user

USER 10001

# This will make sure that we always run python from our venv instead
RUN echo "alias python='uv run python'" >> /home/user/.bashrc