apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-infrastructure-viewer-platform-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-infrastructure-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: platform-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-project-viewer-platform-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-project-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: platform-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-user-cross-project-viewer-platform-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-user-cross-project-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: platform-users
---