---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: builder-el
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: tb-commit
      interceptors:
        - params:
            - name: filter
              value: has(body.commits) && body.object_kind == 'push'
            - name: overlays
              value: null
          ref:
            kind: ClusterInterceptor
            name: cel
      name: commit-trig
      template:
        ref: builder-run-build
    
    - bindings:
        - kind: TriggerBinding
          ref: tb-tag
      interceptors:
        - params:
            - name: filter
              value: body.object_kind == 'tag_push'
            - name: overlays
              value:
                - expression: 'body.ref.split(''/'')[2]'
                  key: tag_version
          ref:
            kind: ClusterInterceptor
            name: cel
      name: tag-trig-preprod
      template:
        ref: builder-run-tag
    
    - bindings:
        - kind: TriggerBinding
          ref: tb-release
      interceptors:
        - params:
            - name: filter
              value: body.object_kind == 'release'
          ref:
            kind: ClusterInterceptor
            name: cel
      name: tag-trig-prod
      template:
        ref: builder-run-release