---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rhadp-builder-build
  labels:
    type: pipeline
    #backstage.io/kubernetes-id: rhadp-builder
spec:
  params:
    - name: source-repo
      description: source repo that contains the application code
      type: string
    - name: source-branch
      description: source branch to build from
      default: "main"
      type: string
    
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.source-repo)
        - name: REVISION
          value: $(params.source-branch)
      taskRef:
        name: git
      workspaces:
        - name: output
          workspace: source-folder

  workspaces:
    - name: source-folder
    - name: docker-config