---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rhadp-builder-build
  labels:
    type: pipeline
    #backstage.io/kubernetes-id: rhadp-builder
spec:
  params:
    - name: source-repo
      description: source repo that contains the application code
      type: string
    - name: source-branch
      description: source branch to build from
      default: "main"
      type: string
    - name: build-stage
      description: Stage of the build process (e.g. develop, release)
      default: "default"
      type: string

  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.source-repo)
        - name: REVISION
          value: $(params.source-branch)
      taskRef:
        name: git
      workspaces:
        - name: output
          workspace: source-folder

    - name: prepare-build
      params:
        - name: build-stage
          value: $(params.build-stage)
      taskRef:
        kind: Task
        name: parse-aib-ci
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source-folder

    - name: automotive-image-builder
      params:
        - name: manifest-file
          value: $(tasks.prepare-build.results.manifest-file)
        - name: distro
          value: $(tasks.prepare-build.results.distro)
        - name: arch
          value: $(tasks.prepare-build.results.arch)
        - name: target
          value: $(tasks.prepare-build.results.target)
        - name: mode
          value: $(tasks.prepare-build.results.mode)
        - name: export_format
          value: $(tasks.prepare-build.results.export_format)

      taskRef:
        kind: Task
        name: aib-builder
      runAfter:
        - prepare-build
      workspaces:
        - name: source
          workspace: source-folder
        - name: dockerconfig
          workspace: docker-config

  workspaces:
    - name: source-folder
    - name: docker-config
