---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: builder-build
  labels:
    type: pipeline
spec:
  params:
    - name: source-repo
      description: source repo that contains the application code
      type: string
    - name: source-branch
      description: source branch to build from
      type: string
    - name: output-image
      description: reference of the image that will get created
      type: string
    - description: Component id
      name: component-id
      type: string
    - name: build-stage
      description: Stage of the build process
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.source-repo)
        - name: revision
          value: $(params.source-branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-folder

    - name: build-container
      params:
        - name: IMAGE
          value: $(params.output-image):$(params.source-branch)
        - name: CONTEXT
          value: ./src
        - name: DOCKERFILE
          value: ./Containerfile
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source-folder
        - name: dockerconfig
          workspace: docker-config

    - name: tag-container
      params:
        - name: source-image-tag
          value: $(params.output-image):$(params.source-branch)
        - name: target-image-tag
          value: $(params.output-image):latest
      runAfter:
        - build-container
      taskRef:
        kind: ClusterTask
        name: tag-image
      workspaces:
        - name: dockerconfig
          workspace: docker-config
        
    - name: deploy
      params:
        - name: COMPONENT_ID
          value: $(params.component-id)
      runAfter:
        - tag-container
      taskRef:
        kind: Task
        name: resync

  workspaces:
    - name: source-folder
    - name: docker-config
