kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webhook-github
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: el-github
spec:
  #host: webhook-rhadp-builder{{ .Values.app.cluster }}
  to:
    kind: Service
    name: el-github
    weight: 100
  port:
    targetPort: http-listener
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
