kind: Task
apiVersion: tekton.dev/v1
metadata:
  name: s3-upload
spec:
  params:
    - name: source
      description: "The source file"
      type: string
    - name: destination
      description: "The destination file"
      type: string
    - name: bucket
      description: "The S3 bucket name"
      type: string
      default: "rhadp-aib-cdn"

    # secrets
    - name: aws-secrets-ref
      description: "Secret with the access key and secret key"
      type: string
      default: "aws-credentials"
    
    # scripts configuration
    - name: script
      description: "Script to be executed"
      type: string
      default: "/home/user/s3-upload.py"

  steps:
    - name: s3-upload
      image: ghcr.io/rhadp/pipeline:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: $(params.aws-secrets-ref)
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: $(params.aws-secrets-ref)
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: aws_default_region
              name: $(params.aws-secrets-ref)

      script: |
        #!/usr/bin/env bash

        set -eux

        # run the script
        python "$(params.script)" $(params.source) -b $(params.bucket) -d $(params.destination)

  workspaces:
    - name: source