kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: build-traditional
spec:
  params:
    # job parameters
    - name: job_id
      description: "the reference used to track the job and access its assets"
      type: string
      default: ""
    - name: component_id
      description: "the component_id the job belongs to"
      type: string
      default: ""
    # aib build parameters
    - name: manifest-file
      description: "manifest file to build"
      type: string
      default: "manifests/simple.aib.yml"
    - name: distro
      type: string
      default: "autosd10-sig"
    - name: arch
      type: string
      default: "aarch64"
    - name: target
      type: string
      default: "qemu"
    - name: mode
      type: string
      default: "package"
    - name: format
      type: string
      default: "qcow2"
  results:
    - description: Name of the image file
      name: image-name
      type: string
    - description: Full path of the image file
      name: image-path
      type: string

  steps:
    - name: aib-build
      image: ghcr.io/rhadp/automotive-image-builder
      # "quay.io/centos-sig-automotive/automotive-image-builder:latest"
      
      #resources:
      #  requests:
      #    memory: "12Gi"
      #    cpu: "1500m"
      #  limits:
      #    memory: "12Gi"
      script: |
        #!/usr/bin/env bash

        set -eux

        OSBUILD_PATH="/usr/bin/osbuild"
        STORE_PATH="/_build"
        RUN_TMP_PATH="/run/osbuild/"

        mkdir -p "$STORE_PATH"
        mkdir -p "$RUN_TMP_PATH"

        if mountpoint -q "$OSBUILD_PATH"; then
            exit 0
        fi

        ROOT_TYPE="system_u:object_r:root_t:s0"
        chcon "$ROOT_TYPE" "$STORE_PATH"

        INSTALL_TYPE="system_u:object_r:install_exec_t:s0"
        if ! mountpoint -q "$RUN_TMP_PATH"; then
          mount -t tmpfs tmpfs "$RUN_TMP_PATH"
        fi

        DEST_PATH="$RUN_TMP_PATH/osbuild"
        cp -p "$OSBUILD_PATH" "$DEST_PATH"
        chcon "$INSTALL_TYPE" "$DEST_PATH"

        mount --bind "$DEST_PATH" "$OSBUILD_PATH"

        cd $(workspaces.source.path)

        # podman credentials
        if [[ "$(workspaces.dockerconfig.bound)" == "true" ]]; then

          # if config.json exists at workspace root, we use that
          if test -f "$(workspaces.dockerconfig.path)/config.json"; then
            export DOCKER_CONFIG="$(workspaces.dockerconfig.path)"

          # else we look for .dockerconfigjson at the root
          elif test -f "$(workspaces.dockerconfig.path)/.dockerconfigjson"; then
            cp "$(workspaces.dockerconfig.path)/.dockerconfigjson" "$HOME/.docker/config.json"
            export DOCKER_CONFIG="$HOME/.docker"

          # need to error out if neither files are present
          else
            echo "neither 'config.json' nor '.dockerconfigjson' found at workspace root"
            exit 1
          fi
        fi

        # build the image

        MANIFEST_FILE=$(workspaces.source.path)/$(params.manifest-file)
        
        # Determine file extension
        if [ "$(params.format)" = "raw" ]; then
          file_extension=".raw"
        elif [ "$(params.format)" = "qcow2" ]; then
          file_extension=".qcow2"
        else
          file_extension=".$(params.format)"
        fi

        CANONICAL_NAME=$(params.distro)-$(params.target)
        EXPORT_FILE_NAME=${CANONICAL_NAME}${file_extension}

        OSBUILD_CMD="automotive-image-builder --verbose build-traditional \
          --distro $(params.distro) \
          --target $(params.target) \
          --format $(params.format) \
          --arch=$(params.arch) \
          --build-dir=/_build \
          --osbuild-manifest=/output/build.json \
          $MANIFEST_FILE \
          /output/${EXPORT_FILE_NAME}"

        echo "Running the build command: $OSBUILD_CMD"
        $OSBUILD_CMD

        #pushd /output
        #ln -sf ./${EXPORT_FILE_NAME} ./disk.img

        # copying build artifacts to shared workspace...
        
        mkdir -p $(workspaces.source.path)/binaries
        
        cp -v /output/${EXPORT_FILE_NAME} $(workspaces.source.path)/binaries/ || echo "Failed to copy ${EXPORT_FILE_NAME}"

        #cp -vL /output/disk.img $(workspaces.source.path)/binaries/${CANONICAL_NAME}${file_extension} || echo "Failed to copy disk.img"

        #pushd $(workspaces.source.path)
        #ln -sf ${EXPORT_FILE_NAME} disk.img
        #popd

        cp -v /output/build.json $(workspaces.source.path)/binaries/build.json || echo "Failed to copy build.json"

        echo -n "$EXPORT_FILE_NAME" > $(results.image-name.path)
        echo -n "$(workspaces.source.path)/binaries/$EXPORT_FILE_NAME" > $(results.image-path.path)

      securityContext:
        capabilities: {}
        privileged: true
        seLinuxOptions:
          type: unconfined_t
      
      volumeMounts:
        - mountPath: /_build
          name: build-dir
        - mountPath: /output
          name: output-dir
        - mountPath: /run/osbuild
          name: run-dir
        - mountPath: /dev
          name: dev
  
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 10Gi
      name: build-dir
    - emptyDir: {}
      name: output-dir
    - emptyDir: {}
      name: run-dir
    - hostPath:
        path: /dev
      name: dev

  workspaces:
    - name: source
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true