kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: build-traditional
spec:
  params:
    # job parameters
    - name: JOB_ID
      description: "the reference used to track the job and access its assets"
      type: string
      default: ""
    # aib build parameters
    - name: MANIFEST_FILE
      description: "manifest file to build"
      type: string
      default: "manifests/simple.aib.yml"
    - name: DISTRO
      type: string
      default: "autosd10-sig"
    - name: ARCH
      type: string
      default: "aarch64"
    - name: TARGET
      type: string
      default: "qemu" 
    - name: EXPORT_FORMAT
      type: string
      default: "qcow2"
  results:
    - description: Name of the image file
      name: IMAGE_NAME
      type: string
    - description: Full path of the image file
      name: IMAGE_PATH
      type: string

  steps:
    - name: aib-build
      image: quay.io/centos-sig-automotive/automotive-image-builder:latest
      # ghcr.io/rhadp/automotive-image-builder
      # quay.io/centos-sig-automotive/automotive-image-builder:latest
      
      resources:
        requests:
          memory: "4Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "2"

      script: |
        #!/usr/bin/env bash

        set -eux

        OSBUILD_PATH="/usr/bin/osbuild"
        STORE_PATH="/_build"
        RUN_TMP_PATH="/run/osbuild/"

        mkdir -p "$STORE_PATH"
        mkdir -p "$RUN_TMP_PATH"

        if mountpoint -q "$OSBUILD_PATH"; then
            exit 0
        fi

        ROOT_TYPE="system_u:object_r:root_t:s0"
        chcon "$ROOT_TYPE" "$STORE_PATH"

        INSTALL_TYPE="system_u:object_r:install_exec_t:s0"
        if ! mountpoint -q "$RUN_TMP_PATH"; then
          mount -t tmpfs tmpfs "$RUN_TMP_PATH"
        fi

        DEST_PATH="$RUN_TMP_PATH/osbuild"
        cp -p "$OSBUILD_PATH" "$DEST_PATH"
        chcon "$INSTALL_TYPE" "$DEST_PATH"

        mount --bind "$DEST_PATH" "$OSBUILD_PATH"

        cd $(workspaces.source.path)

        # podman credentials
        if [[ "$(workspaces.dockerconfig.bound)" == "true" ]]; then

          # if config.json exists at workspace root, we use that
          if test -f "$(workspaces.dockerconfig.path)/config.json"; then
            export DOCKER_CONFIG="$(workspaces.dockerconfig.path)"

          # else we look for .dockerconfigjson at the root
          elif test -f "$(workspaces.dockerconfig.path)/.dockerconfigjson"; then
            cp "$(workspaces.dockerconfig.path)/.dockerconfigjson" "$HOME/.docker/config.json"
            export DOCKER_CONFIG="$HOME/.docker"

          # need to error out if neither files are present
          else
            echo "neither 'config.json' nor '.dockerconfigjson' found at workspace root"
            exit 1
          fi
        fi

        # build the image

        MANIFEST_FILE=$(workspaces.source.path)/$(params.MANIFEST_FILE)
        CANONICAL_NAME=$(params.DISTRO)-$(params.TARGET)
        EXPORT_FILE_NAME=${CANONICAL_NAME}.$(params.EXPORT_FORMAT)

        OSBUILD_CMD="automotive-image-builder --verbose build-traditional \
          --distro $(params.DISTRO) \
          --target $(params.TARGET) \
          --format $(params.EXPORT_FORMAT) \
          --arch=$(params.ARCH) \
          --build-dir=/_build \
          --osbuild-manifest=/output/build.json \
          $MANIFEST_FILE \
          /output/${EXPORT_FILE_NAME}"

        echo "Running the build command: $OSBUILD_CMD"
        $OSBUILD_CMD

        # copying build artifacts to shared workspace...
        
        mkdir -p $(workspaces.source.path)/binaries
        
        cp -v /output/${EXPORT_FILE_NAME} $(workspaces.source.path)/binaries/ 
        cp -v /output/build.json $(workspaces.source.path)/binaries/build.json

        echo -n "$EXPORT_FILE_NAME" > $(results.IMAGE_NAME.path)
        echo -n "$(workspaces.source.path)/binaries/$EXPORT_FILE_NAME" > $(results.IMAGE_PATH.path)

      securityContext:
        capabilities: {}
        privileged: true
        seLinuxOptions:
          type: unconfined_t
      
      volumeMounts:
        - mountPath: /_build
          name: build-dir
        - mountPath: /output
          name: output-dir
        - mountPath: /run/osbuild
          name: run-dir
        - mountPath: /dev
          name: dev
  
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 10Gi
      name: build-dir
    - emptyDir: {}
      name: output-dir
    - emptyDir: {}
      name: run-dir
    - hostPath:
        path: /dev
      name: dev

  workspaces:
    - name: source
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true