---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: builder-run-build
spec:
  params:
    - name: git-revision
      description: The git revision
      default: "main"
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: ""

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: builder-build-
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
          - name: component-id
            value: builder
          - name: build-stage
            value: "default"
        pipelineRef:
          name: builder-build
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
          - name: docker-config
            emptyDir: {}

