apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tb-github-push
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-commit-message
      value: $(body.head_commit.message)
    - name: git-repo-url
      value: $(body.repository.html_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-repo-fullname
      value: $(body.repository.full_name)
    - name: pusher-name
      value: $(body.pusher.name)