---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: builder-run-tag
spec:
  params:
    - name: git-revision
      description: The git revision
      default: "main"
    - name: git-repo-url
      description: The repo url
    - name: destination-tag
      description: The destination tag
   
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: builder-test-
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: tag
            value: $(tt.params.destination-tag)
          - name: component-id
            value: builder
          - name: build-stage
            value: "test"
        pipelineRef:
          name: builder-test
        serviceAccountName: pipeline
        timeout: 1h0m0s
        podTemplate:
          nodeSelector:
            kubernetes.io/arch: arm64
          tolerations:
          - key: "metal"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: gp3-csi
                resources:
                  requests:
                    storage: 10Gi
          - name: docker-config
            emptyDir: {}
