apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  labels:
    app.kubernetes.io/name: backstage
  name: auto-developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
