name: build container images
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  QUAY_ORG: quay.io/rhadp

jobs:
  build-image:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: application
            arch: "amd64, arm64"
    runs-on: ${{ matrix.runs-on }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.QUAY_ORG }}/${{ matrix.name }}
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:containers/${{ matrix.name }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
