name: build container images
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  REGISTRY: quay.io
  QUAY_ORG: quay.io/rhadp

jobs:
  build-image:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: application

    runs-on: ${{ matrix.runs-on }}
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: get version
        run: |
          # Check if there are any tags, if not use a default version
          if git describe --tags --exact-match HEAD 2>/dev/null; then
            VERSION=$(git describe --tags --exact-match HEAD)
          elif git describe --tags 2>/dev/null; then
            VERSION=$(git describe --tags)
          else
            VERSION="0.0.0-$(git rev-parse --short HEAD)"
          fi
          VERSION=${VERSION#v} # remove the leading v prefix for version
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}"

      - name: set image tags
        id: set-tags
        run: |
          TAGS="${{ env.QUAY_ORG }}/${{ matrix.name }}:${{ env.VERSION }}"

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="$TAGS,${{ env.QUAY_ORG }}/${{ matrix.name }}:latest"
          fi

          if [[ "${{ github.ref }}" == refs/heads/release-* ]]; then
            RELEASE_BRANCH_NAME=$(basename "${{ github.ref }}")
            TAGS="$TAGS,${{ env.QUAY_ORG }}/${{ matrix.name }}:${RELEASE_BRANCH_NAME}"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      
      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.QUAY_ORG }}/${{ matrix.name }}
      
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: "containers/${{ matrix.name }}"
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
