apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qemu-exporter-role
rules:
  - apiGroups: ["jumpstarter.dev"]
    resources:
      - clients
      - exporteraccesspolicies
      - exporters
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
